import sys
import os

print("aclut2ets2lut.py - a LUT to ETS2-specific LUT generator\nProject link: https://github.com/Ardaninho/aclut2ets2lut \nPlease report bugs to our project link!\n")
if len(sys.argv) != 2:
    print("Usage: python aclut2ets2lut.py <siifile>")
    print("This script will open the input SII file, make a new file called ffb_lut.sii and write the ETS2 specific code for the SII.")
    print("Code made by Ardaninho")
    sys.exit(1)

input_filename = sys.argv[1]
output_filename = 'ffb_lut.sii'

header = "SiiNunit\n# ETS2-specific SII file generated by aclut2ets2lut\n{\ninput_force_feedback_lut : ffb.lut {"
footer = "}\n}"

if not os.path.exists(input_filename):
    print(f"Error: The file {input_filename} does not exist.")
    sys.exit(1)

with open(input_filename, 'r') as infile, open(output_filename, 'w') as outfile:
    print("Opening file...")
    print("Writing header...")
    outfile.write(header + "\n")
    print("Adding output values...")
    for line in infile:
        modified_line = line.split('|')[-1].strip()
        outfile.write(f"output_values[]: {modified_line}\n")
    print("Writing footer...")
    outfile.write(footer)
print("Generation done.")
print(f"Output written to {output_filename}")